services:
  - type: web
    name: baby-gender-predictor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app/app.py
    envVars:
      - key: FLASK_ENV
        value: production
