services:
  - type: web
    name: baby-gender-predictor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app  # Use gunicorn to serve the app
    envVars:
      - key: FLASK_ENV
        value: production
